### PR TITLE
Fix mailchimp status sync bug from airtable to pg

### PR DESCRIPTION
**Pull request by mcchang**
The airtable column name is "Mailchimp Status", with no question mark.
image

### CODE REVIEW

**Review by pcothenet — APPROVED** [review]
Makes sense!

Do you have everything you need to deploy the change?

**Comment by mcchang** [comment]
> Makes sense!
> 
> Do you have everything you need to deploy the change?

I think so - I'll let you know if I get blocked.  Thanks!

**Comment by mcchang** [comment]
Hey @pcothenet, I was mistaken.  It looks like I don't have access to the climatechangemakers serverless org anymore.  I guess I did momentarily when I removed the payment.  Do you mind deploying the airtable to pg lambda for me for now? I will figure out something more sustainable for the future

**Comment by pcothenet** [comment]
So I don't actually have access to the org anymore either. But you don't
actually need the account to deploy.

If you have AWS credentials set up locally, you can just install the
serverless CLI and you should be able to do "serverless deploy" locally
with just the AWS credentials.

Happy to do a quick live session to get it to work (it's not currently set
up on the computer I'm travelling with, but I could deploy it when I get
back on Saturday)

**Comment by mcchang** [comment]
Ah okay. Yeah, I was able to deploy one of the other lambdas yesterday. I
will deploy this one myself as well. Thanks!

Mike

**Pull request merged**
